// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace studentprojectapi.GeneratedModels;

[Table("department")]
[Index("abbreviation", Name = "UQ__departme__496A048406D6DDE6", IsUnique = true)]
[Index("deptname", Name = "UQ__departme__61393B76516C4499", IsUnique = true)]
public partial class department
{
    [Key]
    public Guid deptID { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string deptname { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string abbreviation { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string createdby { get; set; }

    [Column(TypeName = "date")]
    public DateTime createdate { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string modifiedby { get; set; }

    [Column(TypeName = "date")]
    public DateTime? modifieddate { get; set; }

    [InverseProperty("dept")]
    public virtual ICollection<assignment> assignments { get; set; } = new List<assignment>();
}