// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace studentprojectapi.GeneratedModels;

[Table("employee")]
[Index("email", Name = "UQ__employee__AB6E616415A727A9", IsUnique = true)]
public partial class employee
{
    [Key]
    public Guid personID { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string firstname { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string lastname { get; set; }

    public int? phonenumber { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string email { get; set; }

    [Column(TypeName = "date")]
    public DateTime? startdate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? enddate { get; set; }

    public bool? active { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string createdby { get; set; }

    [Column(TypeName = "date")]
    public DateTime createdate { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string modifiedby { get; set; }

    [Column(TypeName = "date")]
    public DateTime modifieddate { get; set; }

    [InverseProperty("person")]
    public virtual ICollection<assignment> assignments { get; set; } = new List<assignment>();
}