// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace studentprojectapi.GeneratedModels;

public partial class studentprojectContext : DbContext
{
    public studentprojectContext()
    {
    }

    public studentprojectContext(DbContextOptions<studentprojectContext> options)
        : base(options)
    {
    }

    public virtual DbSet<assignment> assignments { get; set; }

    public virtual DbSet<department> departments { get; set; }

    public virtual DbSet<employee> employees { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<assignment>(entity =>
        {
            entity.HasKey(e => e.assignmentID).HasName("PK__assignme__52C218C05C24AB07");

            entity.Property(e => e.assignmentID).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.dept).WithMany(p => p.assignments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__assignmen__deptI__4316F928");

            entity.HasOne(d => d.person).WithMany(p => p.assignments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__assignmen__perso__4222D4EF");
        });

        modelBuilder.Entity<department>(entity =>
        {
            entity.HasKey(e => e.deptID).HasName("PK__departme__BE2D26D6B5480060");

            entity.Property(e => e.deptID).HasDefaultValueSql("(newid())");
        });

        modelBuilder.Entity<employee>(entity =>
        {
            entity.HasKey(e => e.personID).HasName("PK__employee__EC7D7D6DEE5B734C");

            entity.Property(e => e.personID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.active).HasDefaultValueSql("((1))");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}