// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace studentprojectapi.GeneratedModels;

public partial class studentprojectContext : DbContext
{
    public studentprojectContext(DbContextOptions<studentprojectContext> options)
        : base(options)
    {
    }
    //tables
    public virtual DbSet<assignment> assignments { get; set; }

    public virtual DbSet<department> departments { get; set; }
    // get employee table
    public virtual DbSet<employee> employees { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<assignment>(entity =>
        {
            entity.HasKey(e => e.assignmentID).HasName("PK__assignme__52C218C0CCAA6769");

            entity.Property(e => e.assignmentID).ValueGeneratedNever();
            entity.Property(e => e.createdby).IsFixedLength();

            entity.HasOne(d => d.dept).WithMany(p => p.assignments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__assignmen__deptI__2D27B809");

            entity.HasOne(d => d.person).WithMany(p => p.assignments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__assignmen__perso__2C3393D0");
        });

        modelBuilder.Entity<department>(entity =>
        {
            entity.HasKey(e => e.deptID).HasName("PK__departme__BE2D26D6B04FCD99");

            entity.Property(e => e.deptID).ValueGeneratedNever();
            entity.Property(e => e.createdby).IsFixedLength();
        });

        modelBuilder.Entity<employee>(entity =>
        {
            entity.HasKey(e => e.personID).HasName("PK__employee__EC7D7D6DDD1BBB37");

            entity.Property(e => e.personID).ValueGeneratedNever();
            entity.Property(e => e.createdby).IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}