//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentWindowsFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignment
    {
        public System.Guid assignmentID { get; set; }
        public System.Guid personID { get; set; }
        public System.Guid deptID { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        public virtual department department { get; set; }
        public virtual employee employee { get; set; }
    }
}
